# Site settings
author: Ricky Rojas
title: Yung Boolean's Travels
header-img: img/home-bg.png
email: rickyrojas19@gmail.com
copyright_name: Ricky Rojas
description: > # this means to ignore newlines until "baseurl:"
  Insight into my journey as a wannabe developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ricky199X

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
